### PR TITLE
Add support for GitHub actions

### PR DESCRIPTION
**Pull request by Smolevich**
- Add ci file for supporting Github Actions

Sometimes test failed with error such as [here](https://travis-ci.org/spiral/roadrunner/jobs/601350886?utm_medium=notification&utm_source=github_status)

Link on success ci jobs you can see [here](https://github.com/Smolevich/roadrunner/commit/14dac9be74e95185a3bf6c724559de5349a1a6e0/checks?check_suite_id=278333602)

### CODE REVIEW

**Comment by wolfy-j** [comment]
Yeah, it suffers the same issue as here https://github.com/spiral/roadrunner/issues/194 :(
We need to rotate RPC ports in tests.

Overall look good! Thank you

**Comment by wolfy-j** [comment]
I'll merge it after https://github.com/spiral/roadrunner/issues/194 will be complete, or we have a high chance of false errors which will be annoying to verify.

**Comment by Smolevich** [comment]
> I'll merge it after #194 will be complete, or we have a high chance of false errors which will be annoying to verify.

I will try to research this problem

**Comment by wolfy-j** [comment]
Thank you. Ping me on Discord if you need some assistance. It will require Golang knowledge.

**Comment by Smolevich** [comment]
@wolfy-j, problem with failed tests was resolved, how do you pass repo-token for codecov.io?
Link on last ci [ pipeline](https://github.com/Smolevich/roadrunner/runs/300035002). Sending codecoverage fails because repo-token is not used
Codecov has action for using in existing workflow https://github.com/codecov/codecov-action

**Comment by wolfy-j** [comment]
Hi, the codecov token is passed automatically by travis.ci. It seems that Codecov does not support Github actions yet. I would disable code-coverage push on Github for now and leave coverage analysis from travis only.

**Comment by wolfy-j** [comment]
FYI, the issue with ports not fixed, it's just rare to occur. :( We have to fix the golang test in order to fix it.

**Comment by Smolevich** [comment]
I mean that problem with failed tests because i change flag occasionally in ci file Github Actions

**Comment by Smolevich** [comment]
> Hi, the codecov token is passed automatically by travis.ci. It seems that Codecov does not support Github actions yet. I would disable code-coverage push on Github for now and leave coverage analysis from travis only.

GIthub Actions doesn't include in support ci [systems](https://docs.codecov.io/docs/supported-ci-providers), but i can use if condition in step in ci
For example, as [here](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsif)

**Comment by Smolevich** [comment]
@wolfy-j i add if condition for code coverage

**Comment by wolfy-j** [comment]
let me rerun travis tests and merge it

**Pull request merged**
