### PR TITLE
feat(http): Distinct app and internal error codes in the handleError function

### LINKED ISSUE #471: [FEATURE REQUEST] Customization of behavior when rr is unable to allocate worker
:wave: @48d90782

follow up after discord discussion 

**Goal** : Distinct error from worker allocation to be able to retry on another rr instance at load balancer level. 

**Current State** : When rr is not able to allocate a worker, it's send a 500, which is not the best option because application that rr serve could also send 500 HTTP code. 

IHMO, rr should give the possibilty to the user to:
- send a 504 - Gateway Timeout (recoverable) 
- send a 502 Bad Gateway (not recoverable)
- Close the connection without responding (In my mind, traefik retry middleware work in this way) - https://doc.traefik.io/traefik/middlewares/retry/#:~:text=The%20Retry%20middleware%20is%20in,regardless%20of%20the%20response%20status.

With this 3 possibilities I think we good, if you see / have another use case, don't hesitate

https://github.com/spiral/roadrunner/blob/5dc83ef5eee77f4d1ef557e5f8b566e75892680d/service/http/handler.go#L134-L151

### PR DESCRIPTION
**Pull request by 48d90782**
This PR introduces distinct error codes for the app and internal RR errors.
Errors: 
```go
roadrunner.ErrNoAssociatedPool
roadrunner.ErrAllocateWorker
roadrunner.ErrWorkerNotReady
roadrunner.ErrEmptyPayload
roadrunner.ErrPoolStopped
roadrunner.ErrWorkerAllocateTimeout
roadrunner.ErrAllWorkersAreDead
```
now associated with the internal error codes. All other errors are application errors.
Some types of errors are impossible to distinguish in the RR1, for example `json.Unmarshall` internal error or similar.
The `.rr.yaml` now contain two more options for the errors.
```yaml
http:
    internalErrorCode: 502,
    appErrorCode: 502
```
Default behavior unchanged (500 error code as before), but now might be overridden.
closes #471

### CODE REVIEW

**Comment by jjsaunier** [comment]
Do you plan to add 

```
internalErrorCode: 'close'
```

which close connection without responding, this is usefull when load balancer deal with rr pool - when LB get closed connection without response, they try to the next

**Comment by 48d90782** [comment]
> Do you plan to add
> 
> ```
> internalErrorCode: 'close'
> ```
> 
> _not sure about the best option to configure it_
> 
> which close connection without responding, this is usefull when load balancer deal with rr pool - when LB get connection is closed without response, they try to the next

Not in the scope of this ticket. This PR distinguishes error codes and adding the possibility to overwrite them via `.rr.yaml`.

**Pull request merged**
