### PR TITLE
Feature: Introduce ServiceStats for HTTP service

### PR DESCRIPTION
**Pull request by ovr**

### CODE REVIEW

**Comment by wolfy-j** [comment]
You can handle all the stats by adding your handler, check http/debug. This way you don’t need to inject new dependency and service can be enabled or disabled.

**Comment by wolfy-j** [comment]
https://github.com/spiral/roadrunner/blob/master/cmd/rr/http/debug.go This is centralized way to do such things and it’s unified across all services.

**Comment by ovr** [comment]
> https://github.com/spiral/roadrunner/blob/master/cmd/rr/http/debug.go This is centralized way to do such things and it’s unified across all services.

👌 

:shipit: Start re-working

**Comment by ovr** [comment]
@wolfy-j For next iterations of stats

Will be great to have stats:

- for all services? (RPC / Statistics)
- We need external API/http server to expose statistics, m?
- More metrics (min/max/avg time for response), count slow queries (add option for configuration)

Any ideas?

Thanks

**Comment by wolfy-j** [comment]
Hi,

if you can jump on Discord we can discuss it in details. Currently, I think the best way will be to write a new Prometheus service (we have on internally) to link to events and expose stats to outside.

Answers:
- for all services? (RPC / Statistics)
**All services (jobs, grpc, http) expose set of events with timings and etc. You can also gain access to list of their workers to collect memory usage and etc.**

- We need external API/http server to expose statistics, m?
- More metrics (min/max/avg time for response), count slow queries (add option for configuration)
**Both of these things can be handled by histogram and value metrics by Prometheus.**

**Comment by wolfy-j** [comment]
I would also recommend developing this service as a separate repository. Similar to GRPC and Jobs.

**Comment by ovr** [comment]
> if you can jump on Discord we can discuss it in details.

Can you please invite? Discord ovr#2008 or email me link on talk@dmtry.me

Thanks

**Comment by wolfy-j** [comment]
Check link in read me :) it’s open

**Pull request closed without merging**
