### PR TITLE
Dockerfile deletion

### PR DESCRIPTION
**Pull request by tarampampam**
# Reason for This PR

dockerfile is no longer needed for this repository

## Description of Changes

- File `./Dockerfile` was removed

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the MIT license.

## PR Checklist

- [x] All commits in this PR are signed (`git commit -s`).
- [x] The reason for this PR is clearly provided (issue no. or explanation).
- [x] The description of changes is clear and encompassing.
- [ ] Any required documentation changes (code and docs) are included in this PR.
- [ ] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [ ] All added/changed functionality is tested.

### CODE REVIEW

**Comment by tarampampam** [comment]
Friendly ping for @48d90782

**Comment by 48d90782** [comment]
Thank you @tarampampam

**Comment by litan1106** [comment]
@tarampampam we could use a dockerfile for development workflow.
ex: debug and test without local go sdk and php setup.

**Comment by 48d90782** [comment]
Hey @litan1106, yeah, you might be right. What do you think @tarampampam ?

**Comment by litan1106** [comment]
for example:
1. setup a dockerfile with golang:1.16-buster as base
2. add php to the dockerfile
3. setup Goland to run remote target via docker (or debug in vscode with docker)
4. debug/test in Goland (or debug/test in vscode)
Done.

**Comment by tarampampam** [comment]
@48d90782 sounds good! Can you create an issue for this with details (describe required features list)?

**Pull request merged**
