### PR TITLE
GitHub actions updated

### PR DESCRIPTION
**Pull request by tarampampam**
This PR contains:

- [x] Ci actions (build) refactoring
- [x] Little `Makefile` fix (my mistake in previous PR)
- [x] Updated minimal required versions of composer packages:
  - `psr/http-factory` (`^1.0` &rarr; `^1.0.1`)
  - `psr/http-message` (`^1.0` &rarr; `^1.0.1`)
  - `laminas/laminas-diactoros` (`^1.3` &rarr; `^1.3.6`)
- [x] Tests using minimal and maximal composer package versions
- [x] Disabling `checkMissingIterableValueType` in `phpstan.neon.dist`
- [x] Some typos (wrong class namespaces and annotations) in PHP files :warning: 
- [x] One improvement in `HttpClient::respond` method (variable type hint overriding fixed)
- [x] Added packages testing on CI:
  - `./service/gzip`
  - `./service/reload`

### CODE REVIEW

**Review by 48d90782 — APPROVED** [review]
lgtm

**Comment by 48d90782** [comment]
@wolfy-j Could you please take a look at PHP part?

**Comment by tarampampam** [comment]
Floating bugs detected:

```
=== RUN   Test_FileExtensionFilter
panic: open 181314289/file3.txt: no such file or directory

goroutine 35 [running]:
github.com/spiral/roadrunner/service/reload.Test_FileExtensionFilter.func3.1(0xc00002d0b0, 0x9)
    /home/runner/work/roadrunner/roadrunner/service/reload/watcher_test.go:213 +0x1a4
created by github.com/spiral/roadrunner/service/reload.Test_FileExtensionFilter.func3
    /home/runner/work/roadrunner/roadrunner/service/reload/watcher_test.go:209 +0x5b
FAIL    github.com/spiral/roadrunner/service/reload    1.023s

=== RUN   Test_Filter_Directory
file: file1.aaa
panic: handled event from watcher in nested dir

goroutine 16 [running]:
github.com/spiral/roadrunner/service/reload.Test_Filter_Directory.func3.2(0xc000072780)
    /home/runner/work/roadrunner/roadrunner/service/reload/watcher_test.go:443 +0x1c0
created by github.com/spiral/roadrunner/service/reload.Test_Filter_Directory.func3
    /home/runner/work/roadrunner/roadrunner/service/reload/watcher_test.go:440 +0x7d
FAIL    github.com/spiral/roadrunner/service/reload    11.030s
```

**Comment by wolfy-j** [comment]
PHP changes looks good.

**Comment by 48d90782** [comment]
Thanks @tarampampam

**Pull request merged**
