### PR TITLE
RR binary in Docker

### LINKED ISSUE #218: RR binary in Docker
Currently for docker images building that contains RR binary I prefer to use:

```dockerfile
# Github: <https://github.com/512k/roadrunner-docker>
FROM 512k/roadrunner:1.4.6 AS roadrunner

FROM php:7.3.7-alpine

COPY --from=roadrunner /usr/bin/rr /usr/bin/rr

RUN ...
```

It works, but maybe we can create `Dockerfile` in this repository and setup image building _(with RR binary)_ using `hub.docker.com`? If this is possible - I will create an PR

### PR DESCRIPTION
**Pull request by tarampampam**
This PR closes #218

Added / changed:

- `.dockerignore` excludes unimportant files for building (docker context)
- `ci-build.yml` imcludes step for image building testing
- `Dockerfile` contains instructions for image building

Required steps after PR merging:

1. @spiralscout must register account on [hub.docker.com](https://hub.docker.com/)
1. [Create repository](https://hub.docker.com/repository/create) on docker.hub and setup:
image
1. Profit!

### CODE REVIEW

**Comment by tarampampam** [comment]
Golang tests fails in master branch too

**Comment by wolfy-j** [comment]
Thank you, let me review it, I need quite a bit of time due to the load at work.

**Comment by wolfy-j** [comment]
I wonder if it makes sense to build it for multiple php versions...

**Comment by tarampampam** [comment]
I think that makes no sense

**Comment by wolfy-j** [comment]
I mean Docker with php installed

**Comment by wolfy-j** [comment]
But overall it could work as well

**Comment by tarampampam** [comment]
Any dependencies should be isolated from each other, if it possible, I think. In this case anyone can build own docker-image with any versions of PHP and RR

**Comment by tarampampam** [comment]
Ping @spiralscout

**Comment by wolfy-j** [comment]
Will be taken care by end of this week.

**Comment by tarampampam** [comment]
@spiralscout can you complete setup on hub.docker.com? _(step 2 wrote in 1st message)_

**Comment by wolfy-j** [comment]
It has been completed, but for some reason, it's not catching the builds. Need some time to dig in.

http://prntscr.com/qfz587

**Comment by tarampampam** [comment]
It's ok, when new release will be published - docker hub build and publish image with required tag =)

**Comment by wolfy-j** [comment]
Then let's wait for a new release. :)

**Pull request merged**
