### PR TITLE
RoadRunner CLI for binary update and config initialization

### LINKED ISSUE #71: Distribute binary through composer
What about include build binary to composer install? 
To update need to do two thing: update composer and update binary. This is not convenient.

### PR DESCRIPTION
**Pull request by Alex-Bond**
Resolves #71 

I tried to create CLI. Waiting for your comments and suggestions.

Tested on MacOS. Works fine.

### CODE REVIEW

**Comment by wolfy-j** [comment]
Thank you, but I was going to write it in vanilla PHP without Symfony/Console or as Composer plugin. This creates a fairly massive dependency just to download a file.

**Comment by Alex-Bond** [comment]
> Thank you, but I was going to write it in vanilla PHP without Symfony/Console or as Composer plugin. This creates a fairly massive dependency just to download a file.

I think i can remove dep, but codebase will be huge. Technically I added dev for almost any version of Symfony/Console, so a possibility of conflict is pretty small.

**Comment by Alex-Bond** [comment]
@wolfy-j I actually checked deps of Symfony/Console and it looks like footprint is pretty small.
Library helping with CUI and commands. I created 2 commands technically and we can add some other commands.

**Comment by wolfy-j** [comment]
The problem is that RR will require Console package (which is widely used in a world) to do utility like operation. It will conflict eventually with someones project.

**Comment by Alex-Bond** [comment]
> The problem is that RR will require Console package (which is widely used in a world) to do utility like operation. It will conflict eventually with someones project.

It requires console of almost any version (2.5 minimum). Before 2.5 there was not Console library, only helper, so we can work with any version.

**Comment by wolfy-j** [comment]
I have added vendor/bin/rr-build which can build custom version of rr (or default) locally based on provided settings. Working on wiki page atm.

**Pull request merged**
