### PR TITLE
Issue #59 update zend-diactoros, remove `http-interop`

### PR DESCRIPTION
**Pull request by alexpts**

### CODE REVIEW

**Comment by wolfy-j** [comment]
Unfortunately, I cannot merge it :(

I have mentioned in a ticket #59 about ticket #45 (https://github.com/spiral/roadrunner/issues/59#issuecomment-448179079) which was about removing Zend dependency and replacing it with http-factory. PSR7 integration would make a full circle after this PR :(

**Comment by alexpts** [comment]
May be better change all arguments must be required and remove zend too...
All users can use custom implementation of PSR-7.

**Comment by alexpts** [comment]
I updated PR. Remove implementation factory. But it breaks backward compatibility.

**Comment by wolfy-j** [comment]
Unfortunately, we can not allow BC without major release (in which I want to include much more features). I will try to deal with this issue, thank you for your PR!

**Pull request closed without merging**
