### PR TITLE
handle body content on http GET method

### PR DESCRIPTION
**Pull request by moeinpaki**
Hi there,

as you know `HTTP` handle body content on `GET` requests, and also `Laravel` support it.
we can allow GET requests to support body contents.

### CODE REVIEW

**Comment by wolfy-j** [comment]
Oh... ok. I'm not really a fan of it but I will merge this PR in 1 week if no objections raised.

P.S. https://stackoverflow.com/questions/978061/http-get-with-request-body

**Comment by Alex-Bond** [comment]
Honestly, I'm kind of against it. GET should not have body content.

**Comment by ariansz** [comment]
I agree that GET should not support body content, but since body content is already supported natively on GET, I think it makes sense that an application server should support it as well and not care if it's fundamentally wrong.

**Comment by irLinja** [comment]
I think it's quite a useful option since folks trying to adopt roadrunner might have legacy projects that can't be changed easily to not send body on GET requests.

**Comment by wolfy-j** [comment]
Democracy wins.

**Pull request merged**
