### PR TITLE
🔥 feat(status): Readiness checks 

### LINKED ISSUE #601: [RFC, RR2] RedinessProbe oriented health check
Current health check passes if there is at least one worker ready or running, this is good to know the application is not in a broken state, however when we have a pool of many servers running roadrunner and a load balancer it would be handy to have another supported mode of operation for the health check, in such mode the health check would only pass if at least one worker is ready to accept new connections and fail if all workers are busy.

### Limitations

The usefulness of this health check is limited, quoting @48d90782 on #595 :

> There is one problem with a such request. Imagine the following situation:
> 
> 1. You made a request to the healthcheck (HC) endpoint.
> 2. HC endpoint return 200OK, because there is at least 1 worker in the state `Ready` at this particular moment.
> 3. Based on this information you are trying to send a request, but receive a 503 (for example) response.
> 
> How is this possible?
> Between p2 and p3 other user made a request and allocate a worker which was previously free. So, your information is outdated because healthcheck can't guarantee, that after you receive a response, workers will still be available.

### Why then?

Some times an application may behave in a way that all workers get stuck on some long running processes, this is not an ideal situation and can cause a bad user experience. When roadrunner has all of it's workers busy a new request will wait an amount of time for a worker to be allocated (defined by `allocateTimeout`), if no worker can attend the request in that time, an error is returned. You can instruct your load balancer to retry the request with another roadrunner instance. In such cases the request may succeed in the end, but the user has experienced a very long time for the request to be answered. If we can detect when a node is busy and stop sending traffic to it until the health check passes again we will be providing a better user experience because we can proactively reduce the number of request that need to fail before being retried by skipping the bad node in the first place.

You can read the [original comment](https://github.com/spiral/roadrunner/issues/595#issuecomment-800261284) where this idea was discussed.

### PR DESCRIPTION
**Pull request by 48d90782**
# Reason for This PR

closes #601 

## Description of Changes

- 🔥 Support Readiness checks (via `/ready`) status plugin endpoint.

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the MIT license.

## PR Checklist

`[Author TODO: Meet these criteria.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [x] All commits in this PR are signed (`git commit -s`).
- [x] The reason for this PR is clearly provided (issue no. or explanation).
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.

### CODE REVIEW

**Comment by 48d90782** [comment]
Hey @hugochinchilla. This PR brings support to the Readiness checks. But at the moment I'm not sure, how to properly return status. If you check different plugins (`?ready=http&ready=rpc`) that is not obvious, which plugin returned `204` status (NoContent, I'm also open for the proposals for the statuses) if I wrote status in the whole response.
So, we should support only 1 plugin per request and create a separate endpoint for the bulk check (???). But I'm not sure at the moment.

**Comment by hugochinchilla** [comment]
Hi @48d90782 , thanks for implementing it so quickly. I'm also not sure what could be the best option. Do I need to monitor RPC if I'm not using it actively? Is it something that is used internally and could make an http request fail because of rpc being not ready?

In my opinion I would let the user decide using the querystring, so if I go to `?ready=http&ready=rpc` it will fail if any of the two is down, but I could use `?ready=http` or `?ready=rpc` if I wan't to check only one plugin. Does it sound good?

**Comment by 48d90782** [comment]
> In my opinion I would let the user decide using the querystring, so if I go to `?ready=http&ready=rpc` it will fail if any of the two is down, but I could use `?ready=http` or `?ready=rpc` if I wan't to check only one plugin. Does it sound good?

Yeah, generally that how it works today with `health`. But yeah, I agree, that the user should decide how to use the query, include only 1 plugin or several.
The second question, I'm not quite sure, what HTTP code to use when there are no workers in the `ready` state. I guess, that the good option will be 204-NoContent.

**Comment by tarampampam** [comment]
@48d90782 

> I guess, that the good option will be 204-NoContent

Why not `503: Unavailable` code? IBM recomendation: <https://cloud.ibm.com/docs/cloud-native?topic=cloud-native-healthcheck#probe-recommendation>

**Comment by 48d90782** [comment]
> @48d90782
> 
> > I guess, that the good option will be 204-NoContent
> 
> Why not `503: Unavailable` code? IBM recomendation: https://cloud.ibm.com/docs/cloud-native?topic=cloud-native-healthcheck#probe-recommendation

Yeah, agree, also a great option.

**Comment by hugochinchilla** [comment]
Although I agree with using 503, it would be a good idea to prepare for systems where the healthCheck expects some specific code and is not configurable.

Maybe we could add an option to override the default status code trough the query string.

For example `?ready=http&ready=rpc&httpUnavailableStatus=503&rpcUnavailableStatus=505`

**Comment by 48d90782** [comment]
> Although I agree with using 503, it would be a good idea to prepare for systems where the healthCheck expects some specific code and is not configurable.
> 
> Maybe we could add an option to override the default status code through the query string.
> 
> For example `?ready=http&ready=rpc&httpUnavailableStatus=503&rpcUnavailableStatus=505`

We can add this option via the configuration for this particular plugin

**Comment by 48d90782** [comment]
Do we really need to distinguish between RPC status code and HTTP?

**Comment by hugochinchilla** [comment]
> Do we really need to distinguish between RPC status code and HTTP?

I don't need this, it was just a suggestion, maybe it could be useful for someone.

**Comment by 48d90782** [comment]
> > Do we really need to distinguish between RPC status code and HTTP?
> 
> I don't need this, it was just a suggestion, maybe it could be useful for someone.

Ok, at the moment let it be one value for both, it the future if someone needs to have separate codes, we can easily add another value in the config.

**Review by wolfy-j — APPROVED** [review]

**Pull request merged**
