### PR TITLE
Cross-reference PHP codebase

### PR DESCRIPTION
**Pull request by wolfy-j**
# Reason for This PR
Fixes: #492 

## Description of Changes
Added composer.json with reference to roadrunner-worker PHP codebase

## License Acceptance
By submitting this pull request, I confirm that my contribution is made under
the terms of the MIT license.

## PR Checklist
- [x] All commits in this PR are signed (`git commit -s`).
- [x] The reason for this PR is clearly provided (issue no. or explanation).
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.

### CODE REVIEW

**Comment by 48d90782** [comment]
@wolfy-j Please, do not delete the PR template, describe the changes to fit the requirements: https://github.com/spiral/roadrunner/blob/2.0/.github/pull_request_template.md

**Review by 48d90782 — CHANGES_REQUESTED** [review]
Please, follow the PR template: https://github.com/spiral/roadrunner/blob/2.0/.github/pull_request_template.md

**Comment by wolfy-j** [comment]
Done.

**Review by 48d90782 — APPROVED** [review]
LGTM!

**Review by 48d90782 — COMMENTED** [review]
LGTM

**Comment by 48d90782** [comment]
linked #368

**Pull request merged**
