### PR TITLE
Explicitly require Curl since bin/rr doesn't work without it

### PR DESCRIPTION
**Pull request by dkarlovi**
https://github.com/spiral/roadrunner/blob/a208e27c9d8f4558328c3931c960f155a02e786f/bin/rr#L41-L44

### CODE REVIEW

**Comment by wolfy-j** [comment]
I think we can move it into dev dependency, thought. It is not required for the runtime.

**Comment by dkarlovi** [comment]
@wolfy-j just what I wrote in #269.

**Comment by 48d90782** [comment]
resolves #269

**Comment by dkarlovi** [comment]
Tests seem flaky. :see_no_evil:

**Comment by 48d90782** [comment]
Thanks for the PR @dkarlovi

**Comment by dkarlovi** [comment]
Thank you both!

**Comment by dkarlovi** [comment]
@wolfy-j we might have jumped the gun on moving it to require-dev: since you're meant to install this package as a requirement, Composer will *not* install / enforce its dev requirements. Meaning, you cannot expect your reqs will be there, this breaks `bin/rr` (downloader). This PR should probably be reverted, sorry about not thinking this through.

Only nice solution that comes to mind is to separate the downloader as a separate package which would then be a dev requirement in the consuming root project, it would enforce all its reqs and would be ignored for production.

**Comment by wolfy-j** [comment]
Let’s keep it in required for now then. We are going to revise the package close to 2.0 to exclude non essential dependencies.

**Pull request merged**
