### PR TITLE
Feature(CI): Lint php code + exec rr get-binary

### PR DESCRIPTION
**Pull request by ovr**

### CODE REVIEW

**Comment by wolfy-j** [comment]
Based on the script error we can either add php-zip as an extension to Travis. OR, disable requirement for ZIP on Linux machines (TAR used in this case).

**Comment by ovr** [comment]
@wolfy-j PR is ready for review/merge, take a looks when you will be available!

Thanks

**Comment by wolfy-j** [comment]
Can you try to make this check https://github.com/spiral/roadrunner/blob/master/src/bin/rr#L36 not required on linux and remove php-zip from travis? I think it should work and it will make installation simpler.

**Comment by ovr** [comment]
> ot required on linux and remove php-zip from travis?

**Comment by wolfy-j** [comment]
Perfect, now it's even easier to install.

**Comment by wolfy-j** [comment]
Thank you!

**Pull request merged**
